//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HFS.TextRes", typeof(TextRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HFS v{0} &quot;{1}&quot; ({2}).
        /// </summary>
        internal static string app_name_version {
            get {
                return ResourceManager.GetString("app_name_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file: {0}.
        /// </summary>
        internal static string param_input {
            get {
                return ResourceManager.GetString("param_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: {0}.
        /// </summary>
        internal static string param_output {
            get {
                return ResourceManager.GetString("param_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown function &quot;{0}&quot;.
        /// </summary>
        internal static string unknown_function {
            get {
                return ResourceManager.GetString("unknown_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; function type not implemented.
        /// </summary>
        internal static string unknown_function_type {
            get {
                return ResourceManager.GetString("unknown_function_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type &quot;{0}&quot; not implemented..
        /// </summary>
        internal static string unknown_param_type {
            get {
                return ResourceManager.GetString("unknown_param_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///-i [filename]: input script
        ///-o [filename | - | null]: output avi uncompressed file name, pipe &quot;-&quot; o &quot;null&quot;
        ///-fl: shows functions list.
        /// </summary>
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
    }
}
